.TH LDSPED.CONF 5 "April 2006" Linux "Linux System Managers Manua"
.SH NAME
ldsped.conf \- Specify the behavior of
.B ldsped.
.SH DESCRIPTION
.LP
The
.B ldsped.conf
file holds nearly all of the configuration data for
.B ldsped
(with the exception of the deamon-option, which can only
be specified on the commandline). 
.br
For the possible options, please read the
.B ldsped.conf.example
file that came with the package, which holds all of the options and their explanation. 
.SH FILES
.LP
/etc/ax25/ldsped.conf
.SH "SEE ALSO"
.BR ldsped (8).
.SH AUTHOR
Lieven De Samblanx, ON7LDS, on7lds@amsat.org
